insert into employees(emp_id, emp_name, emp_salary, emp_hiredate) values(seq_employees.nextval, 'Rodrigo', 15000, sysdate - 10);
insert into employees(emp_id, emp_name, emp_salary, emp_hiredate) values(seq_employees.nextval, 'Diogo', 2000, sysdate - 300);
insert into employees(emp_id, emp_name, emp_salary, emp_hiredate) values(seq_employees.nextval, 'Lucas', 16000, sysdate - 450);
insert into employees(emp_id, emp_name, emp_salary, emp_hiredate) values(seq_employees.nextval, 'Denis', 14000, sysdate - 380);
insert into employees(emp_id, emp_name, emp_salary, emp_hiredate) values(seq_employees.nextval, 'Renata', 20000, sysdate - 930);
insert into employees(emp_id, emp_name, emp_salary, emp_hiredate) values(seq_employees.nextval, 'Bruno', 18000, sysdate - 561);
insert into employees(emp_id, emp_name, emp_salary, emp_hiredate) values(seq_employees.nextval, 'Andre', 13000, sysdate - 340);
insert into employees(emp_id, emp_name, emp_salary, emp_hiredate) values(seq_employees.nextval, 'Filipe', 15000, sysdate - 653);
insert into employees(emp_id, emp_name, emp_salary, emp_hiredate) values(seq_employees.nextval, 'Guilherme', 16000, sysdate - 443);
